stages:
  - build
  - quality
  - test

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: '1' # Optionnel, désactive la télémétrie .NET

image: mcr.microsoft.com/dotnet/sdk:7.0  # Spécifie l'image Docker officielle .NET

before_script:
  - dotnet clean
  - dotnet restore

build:
  stage: build
  script:
    - dotnet build --configuration Release

test:
  stage: test
  script:
    - dotnet test TourGuideTest/TourGuideTest.csproj --logger:"junit;LogFilePath=TourGuideTest/TestResults/test-results.xml"
    - ls -R TourGuideTest/TestResults/
  artifacts:
    when: always
    reports:
      junit: TourGuideTest/TestResults/test-results.xml
    paths:
      - TourGuideTest/TestResults/


quality:
  stage: quality
  allow_failure: true
  script:
    - dotnet tool install -g dotnet-format
    - export PATH="$PATH:/root/.dotnet/tools"
    - dotnet format --verify-no-changes

